# Generated by Django 5.2.3 on 2025-06-12 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcusaMedica',
            fields=[
                ('id_excusa', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('fecha_inicio_ausencia', models.DateField()),
                ('fecha_fin_ausencia', models.DateField()),
                ('motivo', models.TextField()),
                ('archivo_adjunto', models.FileField(upload_to='excusa_pdfs/')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=10)),
                ('observaciones_validacion', models.TextField(blank=True, null=True)),
                ('id_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excusas', to='usuarios.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='CursoAfectado',
            fields=[
                ('id_curso_afectado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_curso', models.CharField(max_length=100)),
                ('codigo_curso', models.CharField(max_length=50)),
                ('grupo', models.CharField(max_length=20)),
                ('fecha_afectada', models.DateField()),
                ('id_excusa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos_afectados', to='excusas.excusamedica')),
            ],
        ),
    ]
