# Generated by Django 5.2.3 on 2025-06-12 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id_facultad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_facultad', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramaAcademico',
            fields=[
                ('id_programa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_programa', models.CharField(max_length=150)),
                ('nivel', models.CharField(choices=[('pregrado', 'Pregrado'), ('posgrado', 'Posgrado'), ('especializacion', 'Especialización'), ('maestria', 'Maestría'), ('doctorado', 'Doctorado')], max_length=20)),
                ('id_facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programas', to='facultades.facultad')),
            ],
        ),
    ]
