# Generated by Django 5.2.3 on 2025-06-12 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facultades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuncionarioValidador',
            fields=[
                ('id_funcionario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=150)),
                ('correo_institucional', models.EmailField(max_length=254, unique=True)),
                ('dependencia', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id_estudiante', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=150)),
                ('codigo_estudiante', models.CharField(max_length=50, unique=True)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('id_programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='facultades.programaacademico')),
            ],
        ),
    ]
